// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0838ab97-a7b3-4815-95ce-3fcc2bad93ef",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_kThED7d8F",
    "aws_user_pools_web_client_id": "6ve58m9f9esj52iv9lt295as6k"
};


export default awsmobile;
